# API spec in YAML
swagger: '2.0'
info:
  title: All APIs
  description: All APIs of the webservices
  version: "1.0.0"
# the domain of the service
# host: api.datascience.ch
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
    /types:
      get:
        summary: Type system
        description: |
          The type system of the graph.
        parameters:
          - name: namespace
            in: query
            description: The namespace of the type.
            required: false
            type: string
          - name: type
            in: query
            description: The name of the type.
            required: false
            type: string
        tags:
          - Types
        responses:
          200:
            description: A type object
            schema:
              $ref: '#/definitions/Type'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    /graph:
      get:
        summary: Get some subgraphs
        description: |
          Get the vertices that correspond to the query, optionaly including its edges
        parameters:
          - name: name
            in: query
            description: The name of the vertex.
            required: false
            type: string
          - name: type
            in: query
            description: The type of the vertex.
            required: false
            type: string
          - name: with_edges
            in: query
            description: If the edges should be included in the response.
            required: false
            type: boolean
        tags:
          - Graph
        responses:
          200:
            description: A graph object
            schema:
              $ref: '#/definitions/Graph'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
definitions:
  Type:
    type: object
    properties:
      namespace:
        type: string
        description: The namespace.
      description:
        type: string
        description: Description of type.
      display_name:
        type: string
        description: Display name of type.
  Graph:
    type: object
    properties:
      edges:
        type: array
        items:
          $ref: '#/definitions/Edge'
      vertices:
        type: array
        items:
          $ref: '#/definitions/Vertex'
  Vertex:
    type: object
    properties:
      id:
        type: string
        description: uuid of the Vertex.
      name:
        type: string
        description: The name of the Vertex.
  Edge:
    type: object
    properties:
      in_id:
        type: string
        description: uuid of the input Vertex.
      out_id:
       type: string
       description: uuid of the output Vertex.
      name:
        type: string
        description: The name of the Edge.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string

