# API spec in YAML
swagger: '2.0'
info:
  title: Graph API
  description: API for interfacing with the knowledge graph
  version: "1.0.0"
# the domain of the service
# host: api.datascience.ch
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /type:
    get:
      summary: Type system
      description: |
        The type system of the graph.
      parameters:
        - name: namespace
          in: query
          description: The namespace of the type.
          required: true
          type: string
        - name: type
          in: query
          description: The name of the type.
          required: true
          type: string
      tags:
        - Types
      responses:
        200:
          description: A type object
          schema:
            type: $ref: '#/definitions/Type'              
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Type:
    type: object
    properties:
      namespace:
        type: string
        description: The namespace.
      description:
        type: string
        description: Description of type.
      display_name:
        type: string
        description: Display name of type.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
