# API spec in YAML
swagger: '2.0'
info:
  title: Definitions
  description: All definitions
  version: "1.0.0"
# the domain of the service
# host: api.datascience.ch
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
consumes:
  - application/json
paths: {}
definitions:
  # Exported definitions
  # Graph
  Key:
    $ref: ../definitions/graph/Key.yaml
  ## Elements
  Vertex:
    $ref: ../definitions/graph/elements/Vertex.yaml
  Edge:
    $ref: ../definitions/graph/elements/Edge.yaml
  VertexProperty:
    $ref: ../definitions/graph/elements/VertexProperty.yaml
  Property:
    $ref: ../definitions/graph/elements/Property.yaml
  Typed:
    $ref: ../definitions/graph/elements/Typed.yaml
  MultiPropertyValue:
    $ref: ../definitions/graph/elements/MultiPropertyValue.yaml
  DataValue:
    $ref: ../definitions/graph/elements/DataValue.yaml
  VertexReference:
    $ref: ../definitions/graph/elements/VertexReference.yaml
  PersistedVertexReference:
    $ref: ../definitions/graph/elements/PersistedVertexReference.yaml
  ### New
  NewVertex:
    $ref: ../definitions/graph/elements/NewVertex.yaml
  ### Persisted
  PersistedVertex:
    $ref: ../definitions/graph/elements/PersistedVertex.yaml
  PersistedEdge:
    $ref: ../definitions/graph/elements/PersistedEdge.yaml
  PersistedMultiPropertyValue:
    $ref: ../definitions/graph/elements/PersistedMultiPropertyValue.yaml
  PersistedVertexProperty:
    $ref: ../definitions/graph/elements/PersistedVertexProperty.yaml
  ## Types
  DataType:
    $ref: ../definitions/graph/types/DataType.yaml
  Cardinality:
    $ref: ../definitions/graph/types/Cardinality.yaml
  ## Mutation
  Mutation:
    $ref: ../definitions/graph/mutation/Mutation.yaml
  MutationResponse:
    $ref: ../definitions/graph/mutation/MutationResponse.yaml
  MutationStatus:
    $ref: ../definitions/graph/mutation/MutationStatus.yaml
  Operation:
    $ref: ../definitions/graph/mutation/Operation.yaml
  CreateVertex:
    $ref: ../definitions/graph/mutation/CreateVertex.yaml

  # Error

  Error:
    $ref: ../definitions/Error.yaml
