# API spec in YAML
swagger: '2.0'
info:
  title: Graph Mutation Service
  description: Mutate the graph
  version: "1.0.0"
# the domain of the service
host: internal.datascience.ch
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/mutation
produces:
  - application/json
consumes:
  - application/json
paths:
  '/mutation':
    $ref: ../paths/mutation/post.yaml
  '/mutation/create_vertex':
    $ref: ../paths/mutation/create-vertex.yaml
  '/mutation/{mutation-uuid}':
    $ref: ../paths/mutation/status.yaml
definitions:
  $ref: ./definitions.yaml#/definitions
