# API spec in YAML
swagger: '2.0'
info:
  title: All APIs
  description: All APIs of the webservices
  version: "1.0.0"
# the domain of the service
# host: api.datascience.ch
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /


definitions: